# Generated by Django 3.0.8 on 2021-03-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('parentesco', models.CharField(choices=[('mama', 'mama'), ('papa', 'papa'), ('hno', 'hermano'), ('hna', 'hermana'), ('esposa', 'esposa'), ('esposo', 'esposo'), ('hijo', 'hijo'), ('hija', 'hija')], max_length=6)),
                ('vive', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=2)),
            ],
        ),
    ]
