# Generated by Django 3.0.8 on 2021-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='parentesco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='vive',
            field=models.CharField(max_length=2),
        ),
    ]
